//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class ChooseQues
{

    private ChooseQuesElem[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("elem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ChooseQuesElem[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ChooseQuesElem
{

    //题目的id
    private string idField;

    //问题
    private string questionField;
    //a选项
    private string answer_aField;
    //b选项
    private string answer_bField;
    //c选项
    private string answer_cField;

    //选中不同的选项触发的结果
    private string value_aField;
    private string value_bField;
    private string value_cField;

    //背景图片的名称
    private string image_nameField;




    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    public string question
    {
        get
        {
            return this.questionField;
        }
        set
        {
            this.questionField = value;
        }
    }

    public string answer_a {

        get {
            return this.answer_aField;
        }
        set {
            this.answer_aField = value;
        }
    }

    public string answer_b
    {

        get
        {
            return this.answer_bField;
        }
        set
        {
            this.answer_bField = value;
        }
    }

    public string answer_c
    {

        get
        {
            return this.answer_cField;
        }
        set
        {
            this.answer_cField = value;
        }
    }

    public string value_a {
        get {
            return this.value_aField;
        }
        set
        {
            this.value_aField = value;
        }
    }
    public string value_b
    {
        get
        {
            return this.value_bField;
        }
        set
        {
            this.value_bField = value;
        }
    }
    public string value_c
    {
        get
        {
            return this.value_cField;
        }
        set
        {
            this.value_cField = value;
        }
    }

    public string image_name {
        get
        {
            return this.image_nameField;
        }
        set
        {
            this.image_nameField = value;
        }
    }

}
    
