//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Story
{

    private StoryElem[] itemsField;
    private string timeField;
    private string placeField;
    private string image_nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("elem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public StoryElem[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    public string time {
        get
        {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }

    public string place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }

    public string image_name {
        get {
            return image_nameField;
        }
        set {
            this.image_nameField = value;
        }
    }


}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class StoryElem
{

    private string nameField;
    private string answerField;
    public string name {
        get
        {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    public string answer {
        get {
            return this.answerField;
        }
        set {
            this.answerField = value;
        }
    }

}
    
